repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.4.10'
  hooks:
    # Run the formatter.
    - id: ruff-format
    # Run the linter.
    - id: ruff
      args: [--fix]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.10.0'
  hooks:
    - id: mypy
      additional_dependencies: ['polars==0.20.10', 'pytest==8.0.1']
      exclude: utils|tpch
- repo: https://github.com/codespell-project/codespell
  rev: 'v2.3.0'
  hooks:
    - id: codespell
      files: \.(py|rst|md)$
      args: [--ignore-words-list=ser]
- repo: local
  hooks:
    - id: check-api-reference
      name: check-api-reference
      pass_filenames: false
      entry: python -m utils.check_api_reference
      language: python
      additional_dependencies: [polars]
    - id: imports-are-banned
      name: import are banned (use `get_pandas` instead of `import pandas`)
      entry: (?<!>>> )import (pandas|polars|modin|cudf)
      language: pygrep
      files: ^narwhals/
